### PR TITLE
Feature/fix typings and styles

### PR DESCRIPTION
**Pull request by artalat**
Fixes: #33

### CODE REVIEW

**Comment by adnan1naeem** [comment]
@artalat  tests are failing due to slider component is not defined. slider component is not registered in material-ui can you tell where is it  being registered?

**Comment by artalat** [comment]
it was removed in bluebase core and added to react native paper.

But material-ui SHOULD have its own Slider: https://github.com/BlueBaseJS/plugin-material-ui/blob/master/src/index.ts#L90

**Comment by artalat** [comment]
@ammarkhan967 when can we close it??

**Comment by taha437** [comment]
@artalat I increased code coverage of this repo from 96 to 99%, but the set target value is 100%. I am unable to write test case for one branch in JsonGraphqlForm.tsx at line 148. Can you please guide me with this.

**Pull request merged**
